import { useState, useEffect, useCallback } from "react";
import ReactMarkdown from "react-markdown";
import remarkGfm from "remark-gfm";
import { PageLayout, Panel } from "zv-ui";

function formatSize(bytes) {
  if (bytes === null) return "";
  if (bytes < 1024) return `${bytes} B`;
  return `${(bytes / 1024).toFixed(1)} KB`;
}

function FolderIcon() {
  return (
    <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
      <path d="M22 19a2 2 0 01-2 2H4a2 2 0 01-2-2V5a2 2 0 012-2h5l2 3h9a2 2 0 012 2z" />
    </svg>
  );
}

function FileIcon({ name }) {
  const isJson = name.endsWith(".json");
  const isMd = name.endsWith(".md");
  return (
    <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke={isJson ? "var(--accent)" : isMd ? "var(--success)" : "currentColor"} strokeWidth="2">
      <path d="M14 2H6a2 2 0 00-2 2v16a2 2 0 002 2h12a2 2 0 002-2V8z" />
      <path d="M14 2v6h6" />
    </svg>
  );
}

export default function VectorPage() {
  const [currentDir, setCurrentDir] = useState("");
  const [entries, setEntries] = useState([]);
  const [loading, setLoading] = useState(true);
  const [selectedFile, setSelectedFile] = useState(null);
  const [fileContent, setFileContent] = useState("");
  const [fileLoading, setFileLoading] = useState(false);

  const loadDir = useCallback(async (dir) => {
    setLoading(true);
    setSelectedFile(null);
    setFileContent("");
    try {
      const res = await fetch(`/api/vector/list?dir=${encodeURIComponent(dir)}`);
      const data = await res.json();
      setEntries(data.entries || []);
      setCurrentDir(dir);
    } catch {
      setEntries([]);
    } finally {
      setLoading(false);
    }
  }, []);

  useEffect(() => {
    loadDir("");
  }, [loadDir]);

  const openFile = async (filePath) => {
    setFileLoading(true);
    setSelectedFile(filePath);
    try {
      const res = await fetch(`/api/vector/read?file=${encodeURIComponent(filePath)}`);
      const data = await res.json();
      setFileContent(data.content || "");
    } catch {
      setFileContent("Error loading file.");
    } finally {
      setFileLoading(false);
    }
  };

  const goUp = () => {
    const parts = currentDir.split("/").filter(Boolean);
    parts.pop();
    loadDir(parts.join("/"));
  };

  const breadcrumbs = ["vector", ...currentDir.split("/").filter(Boolean)];

  const isJson = selectedFile?.endsWith(".json");
  const isMd = selectedFile?.endsWith(".md");

  return (
    <PageLayout
      title="Vector"
      description="Browse the /vector directory — schemas, research artifacts, decisions, and briefs generated by The Box and the Investiture skill chain."
    >
      <div className="zv-vector-browser">
        <div className="zv-vector-listing">
          <Panel>
            <div className="zv-vector-breadcrumb">
              {breadcrumbs.map((crumb, i) => (
                <span key={i}>
                  {i > 0 && <span className="zv-vector-breadcrumb-sep">/</span>}
                  <button
                    type="button"
                    className="zv-vector-breadcrumb-item"
                    onClick={() => {
                      if (i === 0) loadDir("");
                      else loadDir(breadcrumbs.slice(1, i + 1).join("/"));
                    }}
                  >
                    {crumb}
                  </button>
                </span>
              ))}
            </div>

            {loading ? (
              <p style={{ color: "var(--text-muted)", fontSize: "13px", padding: "12px 0" }}>Loading...</p>
            ) : entries.length === 0 ? (
              <p style={{ color: "var(--text-muted)", fontStyle: "italic", fontSize: "13px", padding: "12px 0" }}>Empty directory</p>
            ) : (
              <div className="zv-vector-entries">
                {currentDir && (
                  <button type="button" className="zv-vector-entry" onClick={goUp}>
                    <span className="zv-vector-entry-icon"><FolderIcon /></span>
                    <span className="zv-vector-entry-name">..</span>
                  </button>
                )}
                {entries.map((entry) => (
                  <button
                    key={entry.path}
                    type="button"
                    className={`zv-vector-entry${selectedFile === entry.path ? " active" : ""}`}
                    onClick={() => {
                      if (entry.type === "dir") loadDir(entry.path);
                      else openFile(entry.path);
                    }}
                  >
                    <span className="zv-vector-entry-icon">
                      {entry.type === "dir" ? <FolderIcon /> : <FileIcon name={entry.name} />}
                    </span>
                    <span className="zv-vector-entry-name">{entry.name}</span>
                    {entry.size !== null && (
                      <span className="zv-vector-entry-size">{formatSize(entry.size)}</span>
                    )}
                  </button>
                ))}
              </div>
            )}
          </Panel>
        </div>

        <div className="zv-vector-preview">
          {selectedFile ? (
            <Panel>
              <div className="zv-doctrine-toolbar">
                <div className="zv-doctrine-filename">{selectedFile}</div>
              </div>
              <div className="zv-vector-preview-body">
                {fileLoading ? (
                  <p style={{ color: "var(--text-muted)", fontSize: "13px" }}>Loading...</p>
                ) : isJson ? (
                  <pre className="zv-code">{fileContent}</pre>
                ) : isMd ? (
                  <div className="zv-markdown">
                    <ReactMarkdown remarkPlugins={[remarkGfm]}>{fileContent}</ReactMarkdown>
                  </div>
                ) : (
                  <pre className="zv-code">{fileContent}</pre>
                )}
              </div>
            </Panel>
          ) : (
            <Panel>
              <p style={{ color: "var(--text-muted)", fontStyle: "italic", fontSize: "13px" }}>
                Select a file to preview its contents.
              </p>
            </Panel>
          )}
        </div>
      </div>
    </PageLayout>
  );
}
